### ISSUE TITLE
weka_num_servers_total reports number of containers

### ISSUE THREAD

**Issue by derselbst** [weka/weka-mon#40]
Hello,

I have noticed that `weka_num_servers_total` reports the number of containers rather than the number of (backend-)servers. @vince-weka Could you perhaps clarify this?

We're using Weka 4.3.2.161, but I also saw it in 4.2.9.

In our case it reports 42. And that is the right answer, because we're having 14 backend nodes, each running 3 containers, hence 42.

**Comment by vince-weka** [comment]
Thanks for the reminder - we had a change in terminology, and adjusting the exporter to handle it was missed.   version 2024-07-24 of weka-mon and export:1.7.4 contain the fix.   You can update the docker-compose.yml to use export:1.7.4 manually as well; start/stop the compose and you should be all set.

**Comment by vince-weka** [comment]
My bad - 1.7.3 is the version... 🤦    The lastest currently.
